version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: roommate_postgres
    environment:
      POSTGRES_DB: roommate_trip
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - roommate_network

  redis:
    image: redis:7-alpine
    container_name: roommate_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - roommate_network

  app:
    build: .
    container_name: roommate_backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_NAME: roommate_trip
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      NODE_ENV: development
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/app/uploads
    networks:
      - roommate_network

volumes:
  postgres_data:
  redis_data:

networks:
  roommate_network:
    driver: bridge